const productsItems = [
  
    {
      id: 1,
      title: "Wine - Alicanca Vinho Verde",
      description:
        "Deep necrosis of underlying tissues [deep third degree] with loss of a body part, of foot",
      price: "$223.70",
      stock: 91,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 3,
    },
    {
      id: 2,
      title: "Grapes - Black",
      description: "Diphtheritic cystitis",
      price: "$863.06",
      stock: 16,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 5,
    },
    {
      id: 3,
      title: "Table Cloth 62x120 White",
      description: "After-cataract, obscuring vision",
      price: "$1358.56",
      stock: 12,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 4,
    },
    {
      id: 4,
      title: "Pepper - White, Whole",
      description:
        "Other specified megaloblastic anemias not elsewhere classified",
      price: "$1215.00",
      stock: 31,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 4,
    },
    {
      id: 5,
      title: "Beer - Blue",
      description: "Dysphagia, pharyngoesophageal phase",
      price: "$352.15",
      stock: 61,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 6,
      title: "Wine - Chardonnay Mondavi",
      description:
        "Diabetes with neurological manifestations, type II or unspecified type, not stated as uncontrolled",
      price: "$1369.04",
      stock: 78,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 3,
    },
    {
      id: 7,
      title: "Quiche Assorted",
      description: "Reticulosarcoma, intra-abdominal lymph nodes",
      price: "$1313.38",
      stock: 17,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 8,
      title: "Tomatillo",
      description: "Accidental poisoning by other anti-infectives",
      price: "$1121.21",
      stock: 30,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 5,
    },
    {
      id: 9,
      title: "Ham - Proscuitto",
      description: "Aftercare for healing traumatic fracture of lower arm",
      price: "$1883.23",
      stock: 34,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 1,
    },
    {
      id: 10,
      title: "Lemon Tarts",
      description:
        "Chronic venous embolism and thrombosis of superficial veins of upper extremity",
      price: "$790.18",
      stock: 88,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 11,
      title: "Cookie Double Choco",
      description: "Burn of unspecified degree of trunk, unspecified site",
      price: "$697.14",
      stock: 4,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 2,
    },
    {
      id: 12,
      title: "Soup Campbells - Italian Wedding",
      description: "Abnormality of secretion of glucagon",
      price: "$1475.93",
      stock: 1,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 3,
    },
    {
      id: 13,
      title: "Marsala - Sperone, Fine, D.o.c.",
      description:
        "Transverse or oblique presentation, antepartum condition or complication",
      price: "$1217.90",
      stock: 7,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 5,
    },
    {
      id: 14,
      title: "Anchovy In Oil",
      description: "Contact with and (suspected) exposure to algae bloom",
      price: "$1458.50",
      stock: 97,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 2,
    },
    {
      id: 15,
      title: "Rum - White, Gg White",
      description: "Compression of vein",
      price: "$843.62",
      stock: 25,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 16,
      title: "Apricots - Dried",
      description:
        "Injury to pancreas, multiple and unspecified sites, with open wound into cavity",
      price: "$1807.66",
      stock: 80,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 17,
      title: "Bread - Bagels, Plain",
      description: "Other localized salmonella infections",
      price: "$1184.02",
      stock: 48,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 18,
      title: "Pasta - Penne, Rigate, Dry",
      description: "Contracture of joint, lower leg",
      price: "$1508.26",
      stock: 16,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 1,
    },
    {
      id: 19,
      title: "Muffin - Mix - Creme Brule 15l",
      description:
        "Chronic gouty arthropathy without mention of tophus (tophi)",
      price: "$1572.98",
      stock: 78,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 5,
    },
    {
      id: 20,
      title: "Scampi Tail",
      description: "Loss of teeth due to caries",
      price: "$431.07",
      stock: 74,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 5,
    },
    {
      id: 21,
      title: "Alize Sunset",
      description: "Torsion of testis, unspecified",
      price: "$416.78",
      stock: 14,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 5,
    },
    {
      id: 22,
      title: "Tea - Darjeeling, Azzura",
      description:
        "Cerebrovascular disorders in the puerperium, delivered, with or without mention of antepartum condition",
      price: "$448.84",
      stock: 84,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 23,
      title: "Scallops - 10/20",
      description:
        "Acute leukemia of unspecified cell type, without mention of having achieved remission",
      price: "$724.25",
      stock: 13,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 2,
    },
    {
      id: 24,
      title: "Broom - Push",
      description:
        "Breech presentation without mention of version, antepartum condition or complication",
      price: "$986.99",
      stock: 78,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 2,
    },
    {
      id: 25,
      title: "Longos - Chicken Cordon Bleu",
      description: "Injury due to war operations from pellets (rifle)",
      price: "$735.71",
      stock: 10,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 3,
    },
    {
      id: 26,
      title: "Lemonade - Pineapple Passion",
      description: "Open fracture of multiple sites of metacarpus",
      price: "$1636.93",
      stock: 42,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 27,
      title: "Beef - Rib Roast, Cap On",
      description:
        "Osteopathy resulting from poliomyelitis, pelvic region and thigh",
      price: "$149.88",
      stock: 71,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 2,
    },
    {
      id: 28,
      title: "Burger Veggie",
      description: "Sensory hearing loss, unilateral",
      price: "$747.62",
      stock: 47,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 1,
    },
    {
      id: 29,
      title: "Muffin Mix - Corn Harvest",
      description: "Arthropod-borne hemorrhagic fever, unspecified",
      price: "$950.43",
      stock: 62,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 3,
    },
    {
      id: 30,
      title: "Energy Drink",
      description:
        "Closed fracture of base of skull without mention of intra cranial injury, with loss of consciousness of unspecified duration",
      price: "$351.00",
      stock: 28,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 1,
    },
    {
      id: 31,
      title: "Tea - Earl Grey",
      description: "Spirochetal infection, unspecified",
      price: "$677.79",
      stock: 50,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 4,
    },
    {
      id: 32,
      title: "Lamb - Leg, Boneless",
      description:
        "Retained portions of placenta or membranes, without hemorrhage, unspecified as to episode of care or not applicable",
      price: "$1338.80",
      stock: 95,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 2,
    },
    {
      id: 33,
      title: "Water, Tap",
      description:
        "Genitourinary tuberculosis, unspecified, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically",
      price: "$981.84",
      stock: 62,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 1,
    },
    {
      id: 34,
      title: "Soup - Campbells Beef Stew",
      description: "Activities involving gymnastics",
      price: "$1130.12",
      stock: 5,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 2,
    },
    {
      id: 35,
      title: "Squeeze Bottle",
      description: "Closed fracture of mandible, ramus, unspecified",
      price: "$812.34",
      stock: 36,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 1,
    },
    {
      id: 36,
      title: "Soup - Knorr, Country Bean",
      description: "Malignant neoplasm of parathyroid gland",
      price: "$932.00",
      stock: 21,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 4,
    },
    {
      id: 37,
      title: "Mangoes",
      description: "Injury to abdominal aorta",
      price: "$823.26",
      stock: 71,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 4,
    },
    {
      id: 38,
      title: "Oysters - Smoked",
      description: "Family history of leukemia",
      price: "$824.49",
      stock: 66,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 5,
    },
    {
      id: 39,
      title: "Dawn Professionl Pot And Pan",
      description: "Benign carcinoid tumor of the sigmoid colon",
      price: "$109.94",
      stock: 45,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 2,
    },
    {
      id: 40,
      title: "Napkin - Beverge, White 2 - Ply",
      description:
        "Open fracture of base of skull with intracranial injury of other and unspecified nature, with no loss of consciousness",
      price: "$173.43",
      stock: 7,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 3,
    },
    {
      id: 41,
      title: "Syrup - Kahlua Chocolate",
      description: "Retinal dystrophy in systemic or cerebroretinal lipidoses",
      price: "$959.29",
      stock: 78,
      pictureUrl: "http://dummyimage.com/700x700.png/ff4444/ffffff",
      category: 5,
    },
    {
      id: 42,
      title: "Pants Custom Dry Clean",
      description: "Arrested dental caries",
      price: "$437.41",
      stock: 10,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 43,
      title: "Pasta - Bauletti, Chicken White",
      description: "Cutaneous hemorrhage of fetus or newborn",
      price: "$1851.95",
      stock: 90,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 2,
    },
    {
      id: 44,
      title: "Wine - White, Lindemans Bin 95",
      description:
        "Delayed delivery after artificial rupture of membranes, delivered, with or without mention of antepartum condition",
      price: "$554.93",
      stock: 80,
      pictureUrl: "http://dummyimage.com/700x700.png/cc0000/ffffff",
      category: 1,
    },
    {
      id: 45,
      title: "Chips Potato Salt Vinegar 43g",
      description:
        "Full-thickness skin loss [third degree, not otherwise specified] of axilla",
      price: "$810.71",
      stock: 97,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 46,
      title: "Lobster - Baby, Boiled",
      description: "Marginal corneal ulcer",
      price: "$806.47",
      stock: 4,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 1,
    },
    {
      id: 47,
      title: "Danishes - Mini Cheese",
      description: "Chronic intestinal amebiasis without mention of abscess",
      price: "$743.53",
      stock: 52,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 5,
    },
    {
      id: 48,
      title: "Foie Gras",
      description: "Open fracture of lunate [semilunar] bone of wrist",
      price: "$1454.08",
      stock: 21,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 5,
    },
    {
      id: 49,
      title: "Mushroom - Portebello",
      description: "Malignant neoplasm of specified parts of peritoneum",
      price: "$1523.26",
      stock: 97,
      pictureUrl: "http://dummyimage.com/700x700.png/5fa2dd/ffffff",
      category: 1,
    },
    {
      id: 50,
      title: "Cheese - Grie Des Champ",
      description:
        "Poisoning by other and unspecified viral and rickettsial vaccines",
      price: "$1617.69",
      stock: 10,
      pictureUrl: "http://dummyimage.com/700x700.png/dddddd/000000",
      category: 2,
    },
  ]


export default productsItems;
